still issues with cuda and numba
martin@labolg ~/stage/cl-py-generator/example/12_cupy/source $ python3 -i run_00_cupy.py
python-exec: Invalid impl in /etc/python-exec/python-exec.conf: python3.4
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])
dtype = int64
shape = (2, 5)
strides = (40, 8)
device = <CUDA Device 0>
Traceback (most recent call last):
  File "run_00_cupy.py", line 22, in <module>
    print(add_ufunc(a, b))
  File "/usr/lib64/python3.6/site-packages/numba/cuda/dispatcher.py", line 88, in __call__
    return CUDAUFuncMechanism.call(self.functions, args, kws)
  File "/usr/lib64/python3.6/site-packages/numba/npyufunc/deviceufunc.py", line 291, in call
    cr.launch(func, shape[0], stream, devarys)
  File "/usr/lib64/python3.6/site-packages/numba/cuda/dispatcher.py", line 197, in launch
    func.forall(count, stream=stream)(*args)
  File "/usr/lib64/python3.6/site-packages/numba/cuda/compiler.py", line 249, in __call__
    kernel = self.kernel.specialize(*args)
  File "/usr/lib64/python3.6/site-packages/numba/cuda/compiler.py", line 713, in specialize
    kernel = self.compile(argtypes)
  File "/usr/lib64/python3.6/site-packages/numba/cuda/compiler.py", line 731, in compile
    kernel.bind()
  File "/usr/lib64/python3.6/site-packages/numba/cuda/compiler.py", line 490, in bind
    self._func.get()
  File "/usr/lib64/python3.6/site-packages/numba/cuda/compiler.py", line 371, in get
    ptx = self.ptx.get()
  File "/usr/lib64/python3.6/site-packages/numba/cuda/compiler.py", line 343, in get
    **self._extra_options)
  File "/usr/lib64/python3.6/site-packages/numba/cuda/cudadrv/nvvm.py", line 478, in llvm_to_ptx
    libdevice = LibDevice(arch=opts.get('arch', 'compute_20'))
  File "/usr/lib64/python3.6/site-packages/numba/cuda/cudadrv/nvvm.py", line 354, in __init__
    raise RuntimeError(MISSING_LIBDEVICE_FILE_MSG.format(arch=arch))
RuntimeError: Missing libdevice file for compute_50.
Please ensure you have package cudatoolkit 7.5.
Install package by:

    conda install cudatoolkit=7.5