taichi doesn't build on laptop
/home/martin/src/taichi/include/taichi/math/sifakis_svd.h:67:33: note: in passing argument 10 of ‘void SifakisSVD::svd(float, float, float, float, float, float, float, float, float, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&, float&) [with int sweeps = 5]’
   67 |                          float &u11,
      |                          ~~~~~~~^~~
In file included from /home/martin/src/taichi/include/taichi/math/geometry_util.h:11,
                 from /home/martin/src/taichi/include/taichi/math/math.h:9,
                 from /home/martin/src/taichi/include/taichi/common/dict.h:17,
                 from /home/martin/src/taichi/include/taichi/common/interface.h:8,
                 from /home/martin/src/taichi/include/taichi/common/loader.h:8,
                 from /home/martin/src/taichi/include/taichi/util.h:7,
                 from /home/martin/src/taichi/include/taichi/math/eigen.h:7,
                 from /home/martin/src/taichi/include/taichi/math/svd.cpp:10:
/home/martin/src/taichi/include/taichi/math/linalg.h: In instantiation of ‘taichi::VectorND<dim__, T, ISE>& taichi::VectorND<dim__, T, ISE>::operator=(const taichi::VectorND<dim__, T, ISE>&) [with int dim__ = 4; T = float; taichi::InstSetExt ISE = taichi::InstSetExt::AVX2]’:
/home/martin/src/taichi/include/taichi/math/linalg.h:1042:9:   required from ‘taichi::MatrixND<dim__, T, ISE>::Vector taichi::MatrixND<dim__, T, ISE>::operator*(const Vector&) const [with int dim_ = 4; T_ = float; taichi::InstSetExt ISE_ = taichi::InstSetExt::AVX2; typename std::enable_if<(SIMD_4_32F<dim_, T_, ISE_> && (dim_ == 4)), int>::type <anonymous> = 0; int dim__ = 4; T = float; taichi::InstSetExt ISE = taichi::InstSetExt::AVX2; taichi::MatrixND<dim__, T, ISE>::Vector = taichi::VectorND<4, float, taichi::InstSetExt::AVX2>]’
/home/martin/src/taichi/include/taichi/math/linalg.h:1644:34:   required from here
/home/martin/src/taichi/include/taichi/math/linalg.h:372:11: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘struct taichi::VectorND<4, float, taichi::InstSetExt::AVX2>’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
  372 |     memcpy(this, &o, sizeof(*this));
      |     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
/home/martin/src/taichi/include/taichi/math/linalg.h:154:8: note: ‘struct taichi::VectorND<4, float, taichi::InstSetExt::AVX2>’ declared here
  154 | struct VectorND : public VectorNDBase<dim__, T, ISE> {
      |        ^~~~~~~~
make[2]: *** [CMakeFiles/taichi_core.dir/build.make:212: CMakeFiles/taichi_core.dir/include/taichi/math/svd.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:115: CMakeFiles/taichi_core.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
  Error: Build failed.
  Error: installation failed.