feat(grpc): add structured employee model and gRPC content generation
gemma model doesn't support this

/170_gemini_grpc/src $ uv run python -i 02_structured.py
{'$defs': {'Employee': {'description': 'Represents an employee in an organization.', 'properties': {'name': {'title': 'Name', 'type': 'string'}, 'employee_id': {'title': 'Employee Id', 'type': 'integer'}, 'reports': {'description': 'A list of employees reporting to this employee.', 'items': {'$ref': '#/$defs/Employee'}, 'title': 'Reports', 'type': 'array'}}, 'required': ['name', 'employee_id'], 'title': 'Employee', 'type': 'object'}}, '$ref': '#/$defs/Employee'}
Traceback (most recent call last):
  File "/home/kiel/stage/cl-py-generator/example/170_gemini_grpc/src/02_structured.py", line 46, in <module>
    response = stub.GenerateContent(request, metadata=metadata)
  File "/.venv/lib/python3.13/site-packages/grpc/_channel.py", line 1166, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/.venv/lib/python3.13/site-packages/grpc/_channel.py", line 996, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.RESOURCE_EXHAUSTED
        details = "You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-2.0-flash-lite
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-2.0-flash-lite
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-2.0-flash-lite
Please retry in 32.465507179s."
        debug_error_string = "UNKNOWN:Error received from peer ipv4:74.125.29.95:443 {grpc_message:"You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-2.0-flash-lite\n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-2.0-flash-lite\n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-2.0-flash-lite\nPlease retry in 32.465507179s.", grpc_status:8}"
>
>>>