something is still wrong with jax
ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: Traced<ShapedArray(bool[])>with<DynamicJaxprTrace(level=0/1)>
The problem arose with the `bool` function.
While tracing the function jacfun at /home/martin/.local/lib/python3.9/site-packages/jax/api.py:898, transformed by jit., this concrete value was not available in Python because it depends on the value of the arguments to jacfun at /home/martin/.local/lib/python3.9/site-packages/jax/api.py:898, transformed by jit. at flattened positions [0], and the computation of these values is being staged out (that is, delayed rather than executed eagerly).
 (https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError)