it is not working:
(llm_env) martin@archlinux ~/stage/cl-py-generator/example/117_langchain_azure_openai/source $ python3 -i p00_use_gpt.py
Ask me a question:What is rain?
Traceback (most recent call last):
  File "/home/martin/stage/cl-py-generator/example/117_langchain_azure_openai/source/p00_use_gpt.py", line 22, in <module>
    messages=[langchain.schema.SystemMessage(contents="You are an angry assistant"), langchain.schema.HumanMessage(content=user_input)]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/llm_env/lib/python3.11/site-packages/langchain/load/serializable.py", line 75, in __init__
    super().__init__(**kwargs)
  File "/home/martin/llm_env/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for SystemMessage
content
  field required (type=value_error.missing)