the xml directory was missing the xsd files
INFO:xbrl.helper.connection_manager:200 http://xbrl.fasb.org/us-gaap/2019/elts/us-roles-2019-01-31.xsd
INFO:xbrl.helper.connection_manager:200 https://xbrl.sec.gov/country/2017/country-2017-01-31.xsd
INFO:xbrl.helper.connection_manager:200 http://xbrl.fasb.org/us-gaap/2019/elts/us-gaap-eedm-def-2019-01-31.xml
INFO:xbrl.helper.connection_manager:200 http://xbrl.fasb.org/srt/2019/elts/srt-eedm1-def-2019-01-31.xml
INFO:xbrl.helper.connection_manager:200 https://xbrl.sec.gov/dei/2019/dei-2019-01-31.xsd
Traceback (most recent call last):
  File "/home/martin/stage/cl-py-generator/example/61_edgar/source/./run_02_parse_edgar.py", line 36, in <module>
    inst = parser.parse_instance_locally(str(fn))
  File "/home/martin/.local/lib/python3.9/site-packages/xbrl/instance.py", line 671, in parse_instance_locally
    return parse_xbrl(path, self.cache, instance_url)
  File "/home/martin/.local/lib/python3.9/site-packages/xbrl/instance.py", line 306, in parse_xbrl
    taxonomy: TaxonomySchema = parse_taxonomy(schema_path, cache)
  File "/home/martin/.local/lib/python3.9/site-packages/xbrl/taxonomy.py", line 306, in parse_taxonomy
    linkbase: Linkbase = parse_linkbase(linkbase_path, linkbase_type)
  File "/home/martin/.local/lib/python3.9/site-packages/xbrl/linkbase.py", line 446, in parse_linkbase
    raise LinkbaseNotFoundException(f"Could not find linkbase at {linkbase_path}")
xbrl.LinkbaseNotFoundException: Could not find linkbase at xml/mu-20200528_cal.xml