looks like i have an issue with pyfits package
          File "/usr/lib/python3.10/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
            raise DistutilsError(str(e)) from e
        distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpry736jx1', '--quiet', '--find-links', 'http://stsdas.stsci.edu/download/packages', 'd2to1>=0.2.5']' returned non-zero exit status 1.
        ----------------------------------------
    WARNING: Discarding https://files.pythonhosted.org/packages/b6/96/930b86cd20b30d6cb2c20d90a39df7c3c66aef8f6a3211f153a2d0d44b35/stsci.distutils-0.3.tar.gz#sha256=5af743b67f908fda5d7ebffa2e96d2ff1d7843b6755965a98275f7547d384c06 (from https://pypi.org/simple/stsci-distutils/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Could not find a version that satisfies the requirement stsci.distutils>=0.3 (from versions: 0.2, 0.2.1, 0.2.2, 0.3, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7)
    ERROR: No matching distribution found for stsci.distutils>=0.3
    Traceback (most recent call last):
      File "/usr/lib/python3.10/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/lib64/python3.10/subprocess.py", line 369, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmptpy8ict1', '--quiet', 'stsci.distutils>=0.3']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-y9vf8tvh/pyfits_bb9aa378b4a940a7a6e9dcde65e75cf7/setup.py", line 11, in <module>
        setup(
      File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 785, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 766, in resolve
        dist = best[req.key] = env.best_match(
      File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1051, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1063, in obtain
        return installer(requirement)
      File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 844, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/usr/lib/python3.10/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmptpy8ict1', '--quiet', 'stsci.distutils>=0.3']' returned non-zero exit status 1.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/c0/5d/ffae283cea526bce7c1154e7309a040a3e8c02e973b2360bcfc8f30134ef/pyfits-3.5.tar.gz#sha256=4e668622d5a3c140590bc6cf8222afcd4d133dde3d6beda3b9c3c9539c5acf18 (from https://pypi.org/simple/pyfits/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading pyfits-3.4.tar.gz (1.7 MB)
     |████████████████████████████████| 1.7 MB 12.1 MB/s