without environment:
./manage.py runserver[martin@localhost web]$ ./manage.py startapp posts
CommandError: 'posts' conflicts with the name of an existing Python module and cannot be used as an app name. Please try another name.