pip numba also not working
martin@labolg ~/stage/cl-py-generator/example/12_cupy/source $ python3 -i run_00_cupy.py
python-exec: Invalid impl in /etc/python-exec/python-exec.conf: python3.4
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])
dtype = int64
shape = (2, 5)
strides = (40, 8)
device = <CUDA Device 0>
Traceback (most recent call last):
  File "run_00_cupy.py", line 23, in <module>
    print(add_ufunc(a, b))
  File "/home/martin/.local/lib64/python3.6/site-packages/numba/cuda/dispatcher.py", line 88, in __call__
    return CUDAUFuncMechanism.call(self.functions, args, kws)
  File "/home/martin/.local/lib64/python3.6/site-packages/numba/npyufunc/deviceufunc.py", line 304, in call
    cr.launch(func, shape[0], stream, devarys)
  File "/home/martin/.local/lib64/python3.6/site-packages/numba/cuda/dispatcher.py", line 200, in launch
    func.forall(count, stream=stream)(*args)
  File "/home/martin/.local/lib64/python3.6/site-packages/numba/cuda/compiler.py", line 266, in __call__
    kernel = self.kernel.specialize(*args)
  File "/home/martin/.local/lib64/python3.6/site-packages/numba/cuda/compiler.py", line 810, in specialize
    kernel = self.compile(argtypes)
  File "/home/martin/.local/lib64/python3.6/site-packages/numba/cuda/compiler.py", line 829, in compile
    kernel.bind()
  File "/home/martin/.local/lib64/python3.6/site-packages/numba/cuda/compiler.py", line 543, in bind
    self._func.get()
  File "/home/martin/.local/lib64/python3.6/site-packages/numba/cuda/compiler.py", line 421, in get
    ptx = self.ptx.get()
  File "/home/martin/.local/lib64/python3.6/site-packages/numba/cuda/compiler.py", line 392, in get
    **self._extra_options)
  File "/home/martin/.local/lib64/python3.6/site-packages/numba/cuda/cudadrv/nvvm.py", line 469, in llvm_to_ptx
    libdevice = LibDevice(arch=opts.get('arch', 'compute_20'))
  File "/home/martin/.local/lib64/python3.6/site-packages/numba/cuda/cudadrv/nvvm.py", line 345, in __init__
    raise RuntimeError(MISSING_LIBDEVICE_FILE_MSG.format(arch=arch))
RuntimeError: Missing libdevice file for compute_50.
Please ensure you have package cudatoolkit >= 8.
Install package by:

    conda install cudatoolkit