build(docker): add jemalloc patch for GCC 16 compatibility
create a patch so that i can build jemalloc on my gentoo with gcc 16:
/var/tmp/portage/dev-libs/jemalloc-5.3.0-r2/work/jemalloc-5.3.0/src/jemalloc_cpp.cpp:90:22: error: '__throw_bad_alloc' is not a member of 'std'; did you mean '__throw_bad_cast'?
90 |                 std::__throw_bad_alloc();
|                      ^~~~~~~~~~~~~~~~~
|                      __throw_bad_cast
make: *** [Makefile:503: src/jemalloc_cpp.pic.o] Error 1